name: texfit
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.10
  - pip=23.0.1
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.5
  - pip:
    - jsonlines==3.1.0
    - datasets==2.14.6
    - transformers==4.27.4
    - diffusers==0.17.1
    - accelerate==0.17.1
    - tensorboard==2.12.0
    - opencv-python==4.7.0.72
    - git+https://github.com/openai/CLIP.git